### ISSUE TITLE
The spec site style is corrupted

### ISSUE THREAD

**Issue by filip26** [w3c/vc-di-bbs#138] opened 2024-02-26 18:02 UTC
Please check https://w3c.github.io/vc-di-bbs/  ToC, Terminology, and algorithm style is corrupted. Thanks.

Context:
@davidlehn  vc-di-bbs is including vc-data-integrity terms.html directly, which 
has been removed 2 days ago.
https://github.com/w3c/vc-data-integrity/commits/main/
https://github.com/w3c/vc-di-bbs/blob/main/index.html#L306

**Comment by davidlehn** [comment] 2024-02-26 18:14
@msporny You were doing the vc-data-integrity changes.  Looks like that early failure to load terms.html here might be causing some cascading errors in this spec rendering.  If resources like terms.html and common.js were to be shared with other DI specs, will need to fix that up, and should probably leave comments there noting those are used cross-spec.

**Comment by msporny** [comment] 2024-02-26 20:50
yes, aware of the issue... the problem is here: https://github.com/w3c/vc-di-ecdsa/pull/57#discussion_r1501877823 ... I have to try things, then wait 6 hours to see if the problem was fixed... super annoying way to do spec editing work... this has to do w/ cross-references between specs, and the ReSpec folks wanting me to update to the new version, which then broke everything... The BBS spec can be fixed by doing something like this for now: https://github.com/w3c/vc-di-ecdsa/blob/main/index.html#L141 and https://github.com/w3c/vc-di-ecdsa/blob/main/index.html#L245-L249 -- PRs welcome :)

**Comment by msporny** [comment] 2024-03-03 18:40
Fixed in cfef8e305607d7344a907137dc13c9fd8f6c6213 and published here: https://www.w3.org/TR/2024/WD-vc-di-bbs-20240303/

Everything should be working again. Closing.

**Closed by msporny** 2024-03-03 18:40 UTC
Labels: PR-exists
